#!/bin/sh
# Start SLDGridy with the Python and Qt staged inside the snap.
libdir=""
for d in "$SNAP"/usr/lib/*-linux-gnu; do
  [ -d "$d" ] && libdir="$d"
done
export LD_LIBRARY_PATH="$libdir:$libdir/blas:$libdir/lapack${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}"
export QT_PLUGIN_PATH="$libdir/qt6/plugins"
export PYTHONPATH="$SNAP/usr/share/sldgridy:$SNAP/usr/lib/python3/dist-packages"
export PYTHONDONTWRITEBYTECODE=1
exec "$SNAP/usr/bin/python3" -m sldgridy "$@"
